repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: trailing-whitespace
